## Pytorch demo

A note on tensors:

In [1]:
import torch

tensor_1d = torch.tensor([1, 2, 3])
print("1D Tensor (Vector):")
print(tensor_1d)
print()

tensor_2d = torch.tensor([[1, 2], [3, 4]])
print("2D Tensor (Matrix):")
print(tensor_2d)
print()

random_tensor = torch.rand(2, 3)
print("Random Tensor (2x3):")
print(random_tensor)
print()

zeros_tensor = torch.zeros(2, 3)
print("Zeros Tensor (2x3):")
print(zeros_tensor)
print()

ones_tensor = torch.ones(2, 3)
print("Ones Tensor (2x3):")
print(ones_tensor)

ModuleNotFoundError: No module named 'torch'

PyTorch sensors can be handled like a numpy array:

In [2]:
tensor = torch.tensor([[1, 2], [3, 4], [5, 6]])

element = tensor[1, 0]
print(f"Indexed Element (Row 1, Column 0): {element}")  
slice_tensor = tensor[:2, :]
print(f"Sliced Tensor (First two rows): \n{slice_tensor}")

reshaped_tensor = tensor.view(2, 3)
print(f"Reshaped Tensor (2x3): \n{reshaped_tensor}")

Indexed Element (Row 1, Column 0): 3
Sliced Tensor (First two rows): 
tensor([[1, 2],
        [3, 4]])
Reshaped Tensor (2x3): 
tensor([[1, 2, 3],
        [4, 5, 6]])


Mathematical operations can be applied to tensors:

In [3]:
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor_b = torch.tensor([[10, 20, 30]]) 

broadcasted_result = tensor_a + tensor_b 
print(f"Broadcasted Addition Result: \n{broadcasted_result}")

matrix_multiplication_result = torch.matmul(tensor_a, tensor_a.T)
print(f"Matrix Multiplication Result (tensor_a * tensor_a^T): \n{matrix_multiplication_result}")

Broadcasted Addition Result: 
tensor([[11, 22, 33],
        [14, 25, 36]])
Matrix Multiplication Result (tensor_a * tensor_a^T): 
tensor([[14, 32],
        [32, 77]])


PyTorch can utilise GPU (if available as cuda device):

In [4]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {device}')

tensor_size = (10000, 10000)  
a = torch.randn(tensor_size, device=device)  
b = torch.randn(tensor_size, device=device)  

c = a + b  

print("Result shape (moved to CPU for printing):", c.cpu().shape)

print("Current GPU memory usage:")
print(f"Allocated: {torch.cuda.memory_allocated(device) / (1024 ** 2):.2f} MB")
print(f"Cached: {torch.cuda.memory_reserved(device) / (1024 ** 2):.2f} MB")

Using device: cpu
Result shape (moved to CPU for printing): torch.Size([10000, 10000])
Current GPU memory usage:
Allocated: 0.00 MB
Cached: 0.00 MB


## NN with Pytorch: A minimal example

Look at the snippet to define a tiny NN for binary classification:

In [39]:
import torch.nn as nn

class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(2, 4) # 2 input nodes to 4 hidden nodes (fc: fully connected)
        self.fch = nn.Linear(4, 4) # inner layer hidden 
        self.fc2 = nn.Linear(4, 1)  # 4 hidden nodes to 1 output node

    def forward(self, x):            # forward pass
        x = torch.relu(self.fc1(x))  # activation function 
        x = torch.relu(self.fch(x))
        # x = self.fc2(x)              # no activation function in output layer - produces raw numerical output)
        # second activation could be defined (e.g. sigmoid to match the task - output: probability)
        x = torch.sigmoid(self.fc2(x)) # -> if we want a classificatin task
        return x

Training data = XOR Logic gate (Example provided by PyTorch tutorial).

In [31]:
X_train = torch.tensor([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]]) 
y_train = torch.tensor([[0.0], [1.0], [1.0], [0.0]])

Introduce loss function (``criterion``) and gradient optimiser (``optimizer``):

In [32]:
import torch.optim as optim
model = SimpleNN()

# criterion = nn.MSELoss()  # loss function defined;
criterion = nn.BCELoss()  # for binary classification, e.g. BCELoss

optimizer = optim.SGD(model.parameters(), lr=0.1) # stochastic gradient descent with learning rate 0.1 -> smaller generaly better

In [40]:
for epoch in range(500):
    model.train()

    outputs = model(X_train)
    loss = criterion(outputs, y_train)

    optimizer.zero_grad() # clear existing gradients
    loss.backward() # backpropagation of loss function to optimise gradient
    optimizer.step() # update parameters using SDG

    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch + 1}/500], Loss: {loss.item():.4f}')

Epoch [10/500], Loss: 0.0953
Epoch [20/500], Loss: 0.0922
Epoch [30/500], Loss: 0.0900
Epoch [40/500], Loss: 0.0880
Epoch [50/500], Loss: 0.0855
Epoch [60/500], Loss: 0.0829
Epoch [70/500], Loss: 0.0810
Epoch [80/500], Loss: 0.0794
Epoch [90/500], Loss: 0.0772
Epoch [100/500], Loss: 0.0753
Epoch [110/500], Loss: 0.0733
Epoch [120/500], Loss: 0.0715
Epoch [130/500], Loss: 0.0698
Epoch [140/500], Loss: 0.0683
Epoch [150/500], Loss: 0.0668
Epoch [160/500], Loss: 0.0654
Epoch [170/500], Loss: 0.0640
Epoch [180/500], Loss: 0.0626
Epoch [190/500], Loss: 0.0614
Epoch [200/500], Loss: 0.0601
Epoch [210/500], Loss: 0.0588
Epoch [220/500], Loss: 0.0575
Epoch [230/500], Loss: 0.0563
Epoch [240/500], Loss: 0.0551
Epoch [250/500], Loss: 0.0541
Epoch [260/500], Loss: 0.0531
Epoch [270/500], Loss: 0.0521
Epoch [280/500], Loss: 0.0512
Epoch [290/500], Loss: 0.0503
Epoch [300/500], Loss: 0.0495
Epoch [310/500], Loss: 0.0485
Epoch [320/500], Loss: 0.0475
Epoch [330/500], Loss: 0.0467
Epoch [340/500], Lo

In [41]:
model.eval()
with torch.no_grad():
    test_data = torch.tensor([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])
    predictions = model(test_data)
    print(f'Predictions:\n{predictions}')

Predictions:
tensor([[0.0235],
        [0.9881],
        [0.9148],
        [0.0171]])
