## Pytorch demo

A note on tensors:

In [11]:
import torch

tensor_1d = torch.tensor([1, 2, 3])
print("1D Tensor (Vector):")
print(tensor_1d)
print()

tensor_2d = torch.tensor([[1, 2], [3, 4]])
print("2D Tensor (Matrix):")
print(tensor_2d)
print()

random_tensor = torch.rand(2, 3)
print("Random Tensor (2x3):")
print(random_tensor)
print()

zeros_tensor = torch.zeros(2, 3)
print("Zeros Tensor (2x3):")
print(zeros_tensor)
print()

ones_tensor = torch.ones(2, 3)
print("Ones Tensor (2x3):")
print(ones_tensor)

1D Tensor (Vector):
tensor([1, 2, 3])

2D Tensor (Matrix):
tensor([[1, 2],
        [3, 4]])

Random Tensor (2x3):
tensor([[0.3621, 0.7779, 0.7832],
        [0.3522, 0.8585, 0.1556]])

Zeros Tensor (2x3):
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones Tensor (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])


PyTorch sensors can be handled like a numpy array:

In [12]:
tensor = torch.tensor([[1, 2], [3, 4], [5, 6]])

element = tensor[1, 0]
print(f"Indexed Element (Row 1, Column 0): {element}")  
slice_tensor = tensor[:2, :]
print(f"Sliced Tensor (First two rows): \n{slice_tensor}")

reshaped_tensor = tensor.view(2, 3)
print(f"Reshaped Tensor (2x3): \n{reshaped_tensor}")

Indexed Element (Row 1, Column 0): 3
Sliced Tensor (First two rows): 
tensor([[1, 2],
        [3, 4]])
Reshaped Tensor (2x3): 
tensor([[1, 2, 3],
        [4, 5, 6]])


Mathematical operations can be applied to tensors:

In [13]:
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor_b = torch.tensor([[10, 20, 30]]) 

broadcasted_result = tensor_a + tensor_b 
print(f"Broadcasted Addition Result: \n{broadcasted_result}")

matrix_multiplication_result = torch.matmul(tensor_a, tensor_a.T)
print(f"Matrix Multiplication Result (tensor_a * tensor_a^T): \n{matrix_multiplication_result}")

Broadcasted Addition Result: 
tensor([[11, 22, 33],
        [14, 25, 36]])
Matrix Multiplication Result (tensor_a * tensor_a^T): 
tensor([[14, 32],
        [32, 77]])


PyTorch can utilise GPU (if available as cuda device):

In [14]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {device}')

tensor_size = (10000, 10000)  
a = torch.randn(tensor_size, device=device)  
b = torch.randn(tensor_size, device=device)  

c = a + b  

print("Result shape (moved to CPU for printing):", c.cpu().shape)

print("Current GPU memory usage:")
print(f"Allocated: {torch.cuda.memory_allocated(device) / (1024 ** 2):.2f} MB")
print(f"Cached: {torch.cuda.memory_reserved(device) / (1024 ** 2):.2f} MB")

Using device: cpu
Result shape (moved to CPU for printing): torch.Size([10000, 10000])
Current GPU memory usage:
Allocated: 0.00 MB
Cached: 0.00 MB


## NN with Pytorch: A minimal example

Look at the snippet to define a tiny NN for binary classification:

In [15]:
import torch.nn as nn

class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(2, 4)  # 2 input nodes to 4 hidden nodes (fc: fully connected)
        self.fch = nn.Linear(4, 4)  # 4 hidden nodes to 1 output node
        self.fc2 = nn.Linear(4, 1)
    def forward(self, x):            # forward pass
        x = torch.relu(self.fc1(x))  # activation function 
        x = torch.relu(self.fch(x))
        # x = self.fc2(x)              # no activation function in output layer - produces raw numerical output)
        # second activation could be defined (e.g. sigmoid to match the task - output: probability)
        x = torch.sigmoid(self.fc2(x)) 
        return x

Training data = XOR Logic gate (Example provided by PyTorch tutorial).

In [16]:
X_train = torch.tensor([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]]) 
y_train = torch.tensor([[0.0], [1.0], [1.0], [0.0]])

Introduce loss function (``criterion``) and gradient optimiser (``optimizer``):

In [17]:
import torch.optim as optim
model = SimpleNN()

# criterion = nn.MSELoss()  # loss function defined;
criterion = nn.BCELoss()  # for binary classification, e.g. BCELoss

optimizer = optim.SGD(model.parameters(), lr=0.1) # stochastic gradient descent with learning rate 0.1

In [18]:
for epoch in range(100):
    model.train()

    outputs = model(X_train)
    loss = criterion(outputs, y_train)

    optimizer.zero_grad() # clear existing gradients
    loss.backward() # backpropagation of loss function to optimise gradient
    optimizer.step() # update parameters using SDG

    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch + 1}/100], Loss: {loss.item():.4f}')

Epoch [10/100], Loss: 0.6964
Epoch [20/100], Loss: 0.6942
Epoch [30/100], Loss: 0.6927
Epoch [40/100], Loss: 0.6915
Epoch [50/100], Loss: 0.6904
Epoch [60/100], Loss: 0.6895
Epoch [70/100], Loss: 0.6885
Epoch [80/100], Loss: 0.6875
Epoch [90/100], Loss: 0.6862
Epoch [100/100], Loss: 0.6848


In [19]:
model.eval()
with torch.no_grad():
    test_data = torch.tensor([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])
    predictions = model(test_data)
    print(f'Predictions:\n{predictions}')

Predictions:
tensor([[0.5141],
        [0.5141],
        [0.5139],
        [0.4965]])
